name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required for creating releases and uploading assets

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Build with version
        run: |
          VERSION=$(git describe --tags --always --dirty)
          go build -ldflags "-X main.Version=$VERSION" -o zeta ./cmd/zeta

      - name: Create GitHub Release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          files: zeta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
