name: Release

on:
  push:
    tags:
      - 'v*' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Build with version
        run: |
          VERSION=$(git describe --tags --always --dirty)
          go build -ldflags "-X main.Version=$VERSION" -o zeta ./cmd/zeta

      - name: Upload binary to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./zeta
          asset_name: zeta
          asset_content_type: application/octet-stream
